In [1]:
import numpy as np

t = [1, 3, 5, 6]

print(t[1])
print(type(t[1]))

A = np.array([1, 3, 5, 6])

#print(A[1])
#print(type(A[1]))
B = np.array([5, 6, 1, 2])
print(np.shape(A))
print(np.shape(A.T))  # transposition

3
<class 'int'>
(4,)
(4,)


In [2]:
C = np.vstack([A, B])
print(C)
print(np.shape(C))

[[1 3 5 6]
 [5 6 1 2]]
(2, 4)


In [4]:
D_1 = [3, 7, 8, 9]
D_2 = [8, 10, 3, 4]
D = np.vstack([D_1, D_2])

E = D.T
print(f'{np.shape(C)} x {np.shape(E)}')
F = np.dot(C, E)  #  Matrix x Matrix multiplication
print(F)
print(np.shape(F))

(2, 4) x (4, 2)
[[118  77]
 [ 83 111]]
(2, 2)


In [9]:
print(f'{np.shape(C)} x {np.shape(D)}')
print(C)
print(D)
print()
G = C * D  # element-wise multiplication - matrix sizes must be equal!!!
print(G)

(2, 4) x (2, 4)
[[1 3 5 6]
 [5 6 1 2]]
[[ 3  7  8  9]
 [ 8 10  3  4]]

[[ 3 21 40 54]
 [40 60  3  8]]


In [13]:
O = np.zeros((4,4))
print(O)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
F = np.dot(C, I)
print(F)
G = np.dot(I, C.T)
print(G)

[[1. 3. 5. 6.]
 [5. 6. 1. 2.]]
[[1. 5.]
 [3. 6.]
 [5. 1.]
 [6. 2.]]


In [20]:
H = np.vstack((C, D))
print(H)
print()

H_I = np.linalg.inv(H)
print(H_I)

[[ 1  3  5  6]
 [ 5  6  1  2]
 [ 3  7  8  9]
 [ 8 10  3  4]]

[[ 1.73333333 -1.93333333 -1.46666667  1.66666667]
 [-1.66666667  1.66666667  1.33333333 -1.33333333]
 [ 0.13333333 -2.53333333 -0.26666667  1.66666667]
 [ 0.6         1.6        -0.2        -1.        ]]


In [21]:
J = np.dot(H, H_I)
print(J)

[[ 1.00000000e+00  0.00000000e+00 -3.33066907e-16 -6.66133815e-16]
 [-4.44089210e-16  1.00000000e+00  1.66533454e-16  1.33226763e-15]
 [-3.33066907e-16  8.88178420e-16  1.00000000e+00 -1.88737914e-15]
 [-4.44089210e-16  1.77635684e-15  6.66133815e-16  1.00000000e+00]]
